spring.application.name=edunest

#spring.datasource.url=jdbc:postgresql://localhost:5432/edunest_db
#spring.datasource.username=postgres
#spring.datasource.password=tiger
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#
#server.port=8080


# ================================================================
# SERVER
# ================================================================
server.port=8080

# ================================================================
# DATABASE — PostgreSQL
# ================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/edunest_db
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.datasource.driver-class-name=org.postgresql.Driver

# ================================================================
# JPA / HIBERNATE
# ================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ================================================================
# JWT
# ================================================================
app.jwt.secret=EduNestSuperSecretKeyForJWT2026MustBe256BitsLongAtLeast32Chars
app.jwt.expiration-ms=86400000

# ================================================================
# FILE UPLOAD
# ================================================================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
file.upload-dir=./uploads

# ================================================================
# EMAIL  (for OTP and password reset)
# ================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your_email@gmail.com
spring.mail.password=your_app_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================================================================
# PAGINATION
# ================================================================
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

# ================================================================
# ACTUATOR
# ================================================================
management.endpoints.web.exposure.include=health,info